### ISSUE TITLE
Document the new eared absorbers

### ISSUE THREAD

**Issue by EinarElen** [EinarElen/prototype-geometry#5]
The design and the implementation of the eared absorbers are currently not documented. Since @PeterGy developed them, it makes sense for you to do so. 

Make use of this issue to discuss what you are planning to do, what options you are considering or any questions you are having about how to do things. 

Ideally there are two things you want to achieve with the documentation: 
1. Someone should be able to find out key details without having to look at the GDML code.
2. Someone reading the GDML code should be able to use the documentation to understand the code rather than having to figure things out on their own. 

I will be changing the README-file format soon, I will update you here when this is done so you can get started.

**Comment by PeterGy** [comment]
How do you suggest I add the image to the readme? (Using ![Image](https://files.slack.com/files-pri/T12GGHQSK-F0271BXAZB5/absorber_plate.png "absorber") doesn't seem to do the trick. I suppose the image hosting is the problem, and I want to do it properly. I thought of a few ways but I'd rather ask you before doing something unprofessional. Should I

1. Host the image in a different repo I create only for hosting images?
2. Place the image among the gdml files, and refer to the image location in the md?
3. Host the image in a free image hosting service (maybe imgur)?
4. Something else?

**Comment by EinarElen** [comment]
You can just add the image as a file into the git-repository. In fact, in 699294a68f1b30f16891e91e222b2fd066932fd8 we will create a folder for figures. You can actually create that folder already and as long as you use the same name, git will be happy to merge things together. 

If you are generating your picture using something (e.g. a visualization macro for Geant4 or some Inkscape/paint/PS-file), you can add the code you used to do so into the src-subdirectory in the figures folder. That would make it easier to recreate or creating alternative versions in the future. 

Finally, you commited things directly to master. It would be better to have a branch for this issue and discuss the changes you are proposing before we bring them into master
