### ISSUE TITLE
Trigger copynumbers

### ISSUE THREAD

**Issue by PeterGy** [EinarElen/prototype-geometry#8]
So I documented the trigger copynumbers, and they work perfectly as far as I can tell. They have a copy number and no layer number. But what strikes me as unorganized is that the trigger ones are zero-indexed, while the rest are not. Should I make the trig copynumbers also non-zero indexed? Or add a layer number? 
As far as I can tell, all the copynumber needs to be is not the same as any other object. The fact that they require explicit declaration for something that could apparently be so easily automated gives me the impression that there is more to it, and I'm therefoe overly cautious when changing these things autonomously.

**Comment by EinarElen** [comment]
So for the Hcal, the layer number is a value that is derived from the CopyNumber. I'm not familiar with with the TrigScint-code, so I don't know what makes sense for TrigScint reconstruction. For example, I'm not sure that a layer number even makes sense for the TrigScint stuff. You can either try looking at the code to try and find out how it works or you can check with someone on Slack!
